// front/src/components/sidebar/SocialMedia.vue
<template>
  <div class="connect">
    <v-btn
      v-for="social in socials"
      :key="social.id"
      :href="social.href"
      :title="social.title"
      class="mx-1"
      fab
      dark
      small
    >
      <v-icon
        dark
      >
        {{ linkMap[social.social] }}
      </v-icon>
    </v-btn>
  </div>
</template>

<script>
export default {
  name: 'SocialMedia',
  props: [
    'socials',
  ],
  data: () => ({
    linkMap: {
      fb: 'mdi-facebook',
      twitter: 'mdi-twitter',
      vk: 'mdi-vk',
    },
  }),
};
</script>

<style scoped>
.connect {
  overflow: hidden;
  padding: 32px 0 18px;
  text-align: center;
}
</style>

// front/src/components/sidebar/SocialMedia/index.jsx
import React from 'react';
import { Button } from 'react-bootstrap';
import './SocialMedia.css';

const linkMap = {
  fb: 'mdi-facebook',
  twitter: 'mdi-twitter',
  vk: 'mdi-vk',
}

function SocialMedia({ socials }) {
  return (
    <div className="connect">
      { socials.map((social) => <Button
        key={social.id}
        href={social.href}
        className="mx-1"
      >
        { linkMap[social.social] }  

      </Button>) }
     </div>
  );
}

export default SocialMedia;
