// front/src/admin/forms/ArticleForm.vue
<template>
  <v-container>
    <v-form>
      <v-text-field
        label="Ссылка"
        v-model="slug"
      />
      <v-text-field
        label="Заголовок"
        v-model="title"
      />
      <v-select
        label="Категории"
        v-model="categories"
        :items="categoriesData"
        attach
        chips
        multiple
      />
      <v-text-field
        label="Просмотров"
        readonly
        v-model="viewed"
      />
      <v-date-picker
        full-width
        v-model="date"
      />
      <markdown-preview
        label="Статья"
        v-model="text"
      />

      <v-card-actions>
        <v-btn
          color="success"
          @click="submit"
        >
          Сохранить
        </v-btn>
        <v-btn
          color="primary"
          :to="(slug === 'index') ? '/' : `/about/${slug}`"
        >
          Перейти
        </v-btn>
      </v-card-actions>
    </v-form>
  </v-container>
</template>

<script>
export default {
  name: 'ArticleForm',
  components: {
    MarkdownPreview: () => import('./MarkdownPreview.vue'),
  },
  computed: {
    categoriesData() {
      return this.categoriesLookup.map((category) => ({
        value: category.id,
        text: category.title,
      }));
    },
  },
  data: () => ({
    id: null,
    slug: '',
    title: '',
    viewed: 0,
    date: new Date().toISOString().substr(0, 10),
    categories: null,
    text: '',
  }),
  methods: {
    load(values) {
      this.id = (values && values.id) || null;
      this.slug = (values && values.slug) || '';
      this.title = (values && values.title) || '';
      this.viewed = (values && values.viewed) || 0;
      this.date = (values && values.date && values.date.substr(0, 10))
        || new Date().toISOString().substr(0, 10);
      this.categories = (values && values.categories) || [];
      this.image = (values && values.image) || '';
      this.text = (values && values.text) || '';
    },
    submit() {
      this.$emit('submit', {
        id: this.id,
        values: {
          slug: this.slug,
          title: this.title,
          date: this.date,
          categories: this.categories,
          text: this.text,
        },
      });
    },
  },
  mounted() {
    this.load(this.formValues);
  },
  props: [
    'formValues',
    'categoriesLookup',
  ],
  watch: {
    formValues: 'load',
  },
};
</script>

<style scoped>

</style>

// front/src/admin/Articles/ArticleForm.jsx
import React, { useEffect } from 'react';
import { Button, Form } from 'react-bootstrap';
import { Field, reduxForm } from 'redux-form';
import AdminField from '../fields/AdminField';
import ImageField from '../fields/ImageField';
import MarkdownPreview from '../fields/MarkdownPreview';
import MultipleSelectField from '../fields/MultipleSelectField';

export const FORM_NAME = 'ARTICLE_FORM';

let ArticleForm = ({
  item,
  link,
  handleSubmit,
  initialize,
  initialValues,
  categories,
  onSubmit,
}) => {
  useEffect(() => {
    const toUpdate = item || {};
    let date = new Date(toUpdate.date);
    if (isNaN(date)) {
      date = new Date();
    }
    initialize({
      ...initialValues,
      ...toUpdate,
      date: date.toISOString().substring(0, 10),
    });
  }, [
    item,
    initialize,
    initialValues,
  ]);

  return (
    <Form
      onSubmit={handleSubmit(onSubmit)}
    >
      <Field
        name="slug"
        label="Ссылка"
        component={AdminField}
      />

      <Field
        name="title"
        label="Заголовок"
        component={AdminField}
      />

      <Field
        name="categories"
        label="Категории"
        options={categories}
        component={MultipleSelectField}
      />

      <Field
        name="viewed"
        label="Просмотров"
        readOnly
        component={AdminField}
      />

      <Field
        name="date"
        label="Дата"
        type="date"
        component={AdminField}
      />

      <Field
        name="image"
        label="Изображение"
        component={ImageField}
      />

      <Field
        name="text"
        label="Статья"
        component={MarkdownPreview}
      />

      {link && <Form.Group>
        <Button
          variant="link"
          href={link}
        >
          Перейти
        </Button>
      </Form.Group>}

      <Form.Group>
        <Button
          className="my-2"
          variant="success"
          type="submit"          
        >
          Сохранить
        </Button>
      </Form.Group>
    </Form>
  );
}

ArticleForm = reduxForm({
  form: FORM_NAME,
  initialValues: {
    slug: '',
    title: '',
    viewed: 0,
    categories: [],
    image: '',    
    text: '',
  },
})(ArticleForm);

export default ArticleForm;
