// front/src/components/LatestProjects/index.jsx
import React from 'react';
import { Card } from 'react-bootstrap';
import { Link } from 'react-router-dom';
import './LatestProjects.css';

function LatestProjects({ title, projects, links, children }) {
  return (
    <div className="latest-projects">
      <h3><span>{ title }</span></h3>
      { projects && <ul>
        { projects.map((project, projectId) => <li
          key={projectId}
        >
          <Link to={project.to}>
            <Card
              width="200px"
            >
              { project.image && <img
                src={project.image}
                alt={project.title}
                width="200px"
                height="100px"    
              /> }
              <Card.Body>
                <h5>{ project.title }</h5>
                <h6>Заказчик: { project.client }</h6>
              </Card.Body>
            </Card>
          </Link>
        </li>) }
      </ul> }
    </div>
  );
}

export default LatestProjects;

// front/src/components/LatestProjects.vue
<template>
  <div class="section">
    <h3><span>{{ title }}</span></h3>
    <ul v-if="projects">
      <li
        v-for="(project, projectId) in projects"
        :key="projectId"
      >
        <router-link :to="project.to">
          <img
            :src="project.img"
            :alt="project.title"
          />
        </router-link>

        <span>Project: {{ project.title }}</span>

        <span>Client: {{ project.client }}</span>

        <router-link :to="project.to">Подробнее</router-link>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: 'LatestServices',
  props: [
    'title',
    'projects',
  ],
};
</script>

<style scoped>

</style>
