// front/src/admin/fields/MarkdownPreview/index.jsx
import React, { useCallback, useMemo } from 'react';
import { Col, Form, Row } from 'react-bootstrap';
import markdown from '../../../helpers/markdown';

import './MarkdownPreview.css';

function MarkdownPreview({
  label,
  readOnly=false,
  type='text',
  input: {
    name,
    value,
    onChange,
  },
}) {
  const handleChange = useCallback((event) => {
    onChange(event.target.value);
  }, [onChange]);

  const html = useMemo(() => markdown.render(value || ''), [value]);

  return (
    <Form.Group>
      <Form.Label>{label}</Form.Label>
      <Row>
        <Col>
          <Form.Control
            as="textarea"
            id={name}
            name={name}
            placeholder={label}
            readOnly={readOnly}
            type={type}
            value={value}
            onChange={handleChange}
          />
        </Col>
        <Col>
          <div
            className="markdown-preview"
            dangerouslySetInnerHTML={{
              __html: html,
            }}
          />
        </Col>
      </Row>
    </Form.Group>
  );
}

export default MarkdownPreview;

// front/src/admin/forms/MarkdownPreview.vue
<template>
  <v-row>
    <v-col>
      <v-textarea
        :label="label"
        :value="value"
        @input="onInput"
      />
    </v-col>
    <v-col>
      <div
        class="markdown-preview"
        v-html="html"
      />
    </v-col>
  </v-row>
</template>

<script>
import markdown from '@/helpers/markdown';

export default {
  name: 'MarkdownPreview',
  computed: {
    html() {
      return markdown.render(this.value || '');
    },
  },
  methods: {
    onInput(value) {
      this.$emit('input', value);
    },
  },
  props: [
    'label',
    'value',
  ],
};
</script>

<style scoped>
.markdown-preview {
  max-width: 350px;
  overflow: scroll;
}
</style>
