// front/src/admin/Socials/SocialForm.jsx
import React, { useEffect } from 'react';
import { Button, Form } from 'react-bootstrap';
import { Field, reduxForm } from 'redux-form';
import AdminField from '../fields/AdminField';

export const FORM_NAME = 'SOCIAL_FORM';

let SocialForm = ({
  item,
  handleSubmit,
  initialize,
  initialValues,
  onSubmit,
}) => {
  useEffect(() => {
    const toUpdate = item || {};
    initialize({
      ...initialValues,
      ...toUpdate,
    });
  }, [
    item,
    initialize,
    initialValues,
  ]);

  return (
    <Form
      onSubmit={handleSubmit(onSubmit)}
    >
      <Field
        name="title"
        label="Название"
        component={AdminField}
      />

      <Field
        name="href"
        label="Ссылка"
        component={AdminField}
      />

      <Field
        name="social"
        label="Социальная сеть"
        component={AdminField}
      />

      {item && item.href && <Form.Group>
        <Button
          variant="link"
          href={item.href}
        >
          Перейти
        </Button>
      </Form.Group>}

      <Form.Group>
        <Button
          className="my-2"
          variant="success"
          type="submit"          
        >
          Сохранить
        </Button>
      </Form.Group>
    </Form>
  );
}

SocialForm = reduxForm({
  form: FORM_NAME,
  initialValues: {
    title: '',
    href: '',
    social: '',
  },
})(SocialForm);

export default SocialForm;

// front/src/admin/forms/SocialForm.vue
<template>
  <v-container>
    <v-form>
      <v-text-field
        label="Название"
        v-model="title"
      />
      <v-text-field
        label="Ссылка"
        v-model="href"
      />
      <v-text-field
        label="Социальная сеть"
        v-model="social"
      />
      <v-card-actions>
        <v-btn
          color="success"
          @click="submit"
        >
          Сохранить
        </v-btn>
        <v-btn
          color="primary"
          :href="href"
        >
          Перейти
        </v-btn>
      </v-card-actions>
    </v-form>
  </v-container>
</template>

<script>
export default {
  name: 'SocialForm',
  data: () => ({
    id: null,
    title: '',
    href: '',
    social: '',
  }),
  methods: {
    load(values) {
      this.id = (values && values.id) || null;
      this.title = (values && values.title) || '';
      this.href = (values && values.href) || '';
      this.social = (values && values.social) || '';
    },
    submit() {
      this.$emit('submit', {
        id: this.id,
        values: {
          title: this.title,
          href: this.href,
          social: this.social,
        },
      });
    },
  },
  mounted() {
    this.load(this.formValues);
  },
  props: [
    'formValues',
  ],
  watch: {
    formValues: 'load',
  },
};
</script>

<style scoped>

</style>
