// front/src/admin/Users/UserForm.vue
<template>
  <v-container>
    <v-form>
      <v-text-field
        label="Имя пользователя"
        v-model="username"
      />
      <v-text-field
        label="Пароль"
        type="password"
        v-model="password"
      />
      <v-text-field
        label="Дата регистрации"
        :value="dateFormatter(date)"
        readonly
      />
      <v-card-actions>
        <v-btn
          color="success"
          @click="submit"
        >
          Сохранить
        </v-btn>
      </v-card-actions>
    </v-form>
  </v-container>
</template>

<script>
import dateFormatter from '@/helpers/dateFormatter';

export default {
  name: 'UserForm',
  data: () => ({
    id: null,
    username: '',
    password: '',
    date: new Date(),
  }),
  methods: {
    load(values) {
      this.id = (values && values.id) || null;
      this.username = (values && values.username) || '';
      this.date = (values && values.date) || new Date();
    },
    submit() {
      const values = {
        username: this.username,
      };
      if (this.password) {
        values.password = this.password;
      }
      this.$emit('submit', {
        id: this.id,
        values,
      });
    },
    dateFormatter,
  },
  mounted() {
    this.load(this.formValues);
  },
  props: [
    'formValues',
  ],
  watch: {
    formValues: 'load',
  },
};
</script>

<style scoped>

</style>

// front/src/admin/Users/UserForm.jsx
import React, { useCallback, useEffect, useState } from 'react';
import { Button, Container, Form } from 'react-bootstrap';
import { useNavigate } from 'react-router-dom';
import dateFormatter from '../../helpers/dateFormatter';

function UserForm({
  values,
  onSubmit,
}) {
  const navigate = useNavigate();

  const [id, setId] = useState(null);
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [date, setDate] = useState(new Date());
  
  const handleChangeUsername = useCallback((event) => setUsername(event.target.value), []);
  const handleChangePassword = useCallback((event) => setPassword(event.target.value), []);
  
  const handleSubmit = useCallback(() => {
    const newValues = {
      username,
    };
    if (password) {
      newValues.password = password;
    }
    onSubmit(id, newValues);
    navigate('/admin/user');
  }, [
    navigate,
    id,
    username,
    password,
    onSubmit,
  ]);

  useEffect(() => {
    if (!values) {
      setId(null);
      setUsername('');
      setDate(new Date());  
      return;
    }

    setId(values.id || null);
    setUsername(values.username || '');
    setDate(values.date || new Date());  
  }, [values]);

  return (
    <Container>
      <Form>
        <Form.Group>
          <Form.Label>Имя пользователя</Form.Label>  
          <Form.Control
            placeholder="Имя пользователя"
            value={username}
            onChange={handleChangeUsername}
          />
        </Form.Group>

        <Form.Group>
          <Form.Label>Пароль</Form.Label>  
          <Form.Control
            type="password"
            placeholder="Пароль"
            value={password}
            onChange={handleChangePassword}
          />
        </Form.Group>

        <Form.Group>
          <Form.Label>Дата регистрации</Form.Label>  
          <Form.Control
            placeholder="Дата регистрации"
            value={dateFormatter(date)}
            readOnly
          />
        </Form.Group>
      </Form>

      <Container className="my-2">
        <Button
          variant="success"
          onClick={handleSubmit}
        >
          Сохранить
        </Button>
      </Container>
    </Container>
  );
}

export default UserForm;
