// front/src/admin/forms/WikiForm.vue
<template>
  <v-container>
    <v-form>
      <v-text-field
        label="Ссылка"
        v-model="slug"
      />
      <v-text-field
        label="Заголовок"
        v-model="title"
      />
      <markdown-preview
        label="Статья"
        v-model="text"
      />

      <v-card-actions>
        <v-btn
          color="success"
          @click="submit"
        >
          Сохранить
        </v-btn>
        <v-btn
          color="primary"
          :to="`/pages/${slug}`"
        >
          Перейти
        </v-btn>
      </v-card-actions>
    </v-form>
  </v-container>
</template>

<script>
export default {
  name: 'WikiForm',
  components: {
    MarkdownPreview: () => import('./MarkdownPreview.vue'),
  },
  data: () => ({
    slug: '',
    title: '',
    text: '',
  }),
  methods: {
    loadValues(values) {
      if (!values) {
        return;
      }
      this.slug = values.slug || '';
      this.title = values.title || '';
      this.text = values.text || '';
    },
    submit() {
      this.$emit('submit', {
        slug: this.slug,
        title: this.title,
        text: this.text,
      });
    },
  },
  mounted() {
    this.loadValues(this.formValues);
  },
  props: [
    'formValues',
  ],
  watch: {
    formValues: 'loadValues',
  },
};
</script>

<style scoped>

</style>

// front/src/admin/Wiki/WikiForm.jsx
import React, { useEffect } from 'react';
import { Button, Form } from 'react-bootstrap';
import { Field, reduxForm } from 'redux-form';
import AdminField from '../fields/AdminField';
import MarkdownPreview from '../fields/MarkdownPreview';

export const FORM_NAME = 'WIKI_FORM';

let WikiForm = ({
  item,
  link,
  handleSubmit,
  initialize,
  initialValues,
  categories,
  onSubmit,
}) => {
  useEffect(() => {
    const toUpdate = item || {};
    let date = new Date(toUpdate.date);
    if (isNaN(date)) {
      date = new Date();
    }
    initialize({
      ...initialValues,
      ...toUpdate,
      date: date.toISOString().substring(0, 10),
    });
  }, [
    item,
    initialize,
    initialValues,
  ]);

  return (
    <Form
      onSubmit={handleSubmit(onSubmit)}
    >
      <Field
        name="slug"
        label="Ссылка"
        component={AdminField}
      />

      <Field
        name="title"
        label="Заголовок"
        component={AdminField}
      />

      <Field
        name="text"
        label="Статья"
        component={MarkdownPreview}
      />

      {link && <Form.Group>
        <Button
          variant="link"
          href={link}
        >
          Перейти
        </Button>
      </Form.Group>}

      <Form.Group>
        <Button
          className="my-2"
          variant="success"
          type="submit"          
        >
          Сохранить
        </Button>
      </Form.Group>
    </Form>
  );
}

WikiForm = reduxForm({
  form: FORM_NAME,
  initialValues: {
    slug: '',
    title: '',
    image: '',    
    text: '',
  },
})(WikiForm);

export default WikiForm;
