// front/src/admin/forms/ProjectForm.vue
<template>
  <v-container>
    <v-form>
      <v-text-field
        label="Ссылка"
        v-model="slug"
      />
      <v-text-field
        label="Заголовок"
        v-model="title"
      />
      <v-select
        label="Услуга"
        v-model="serviceId"
        :items="servicesData"
      />
      <v-text-field
        label="Клиент"
        v-model="client"
      />
      <v-text-field
        label="Изображение"
        v-model="image"
      />
      <v-img
        v-if="image"
        :src="image"
      />
      <v-date-picker
        full-width
        v-model="date"
      />
      <markdown-preview
        label="Статья"
        v-model="text"
      />

      <v-card-actions>
        <v-btn
          color="success"
          @click="submit"
        >
          Сохранить
        </v-btn>
        <v-btn
          color="primary"
          :to="`/projects/${slug}`"
        >
          Перейти
        </v-btn>
      </v-card-actions>
    </v-form>
  </v-container>
</template>

<script>
export default {
  name: 'ProjectForm',
  components: {
    MarkdownPreview: () => import('./MarkdownPreview.vue'),
  },
  computed: {
    servicesData() {
      return this.services.map((service) => ({
        value: service.id,
        text: service.title,
      }));
    },
  },
  data: () => ({
    id: null,
    slug: '',
    title: '',
    client: '',
    date: new Date().toISOString().substr(0, 10),
    serviceId: null,
    image: '',
    text: '',
  }),
  methods: {
    load(values) {
      this.id = (values && values.id) || null;
      this.slug = (values && values.slug) || '';
      this.title = (values && values.title) || '';
      this.client = (values && values.client) || '';
      this.date = (values && values.date.substr(0, 10))
        || new Date().toISOString().substr(0, 10);
      this.serviceId = (values && values.serviceId) || null;
      this.image = (values && values.image) || '';
      this.text = (values && values.text) || '';
    },
    submit() {
      this.$emit('submit', {
        id: this.id,
        values: {
          slug: this.slug,
          title: this.title,
          client: this.client,
          date: this.date,
          serviceId: this.serviceId,
          image: this.image,
          text: this.text,
        },
      });
    },
  },
  mounted() {
    this.load(this.formValues);
  },
  props: [
    'formValues',
    'services',
  ],
  watch: {
    formValues: 'load',
  },
};
</script>

<style scoped>

</style>

// front/src/admin/Projects/ProjectForm.jsx
import React, { useEffect } from 'react';
import { Button, Form } from 'react-bootstrap';
import { Field, reduxForm } from 'redux-form';
import AdminField from '../fields/AdminField';
import ImageField from '../fields/ImageField';
import MarkdownPreview from '../fields/MarkdownPreview';
import SelectField from '../fields/SelectField';

export const FORM_NAME = 'PROJECT_FORM';

let ProjectForm = ({
  item,
  link,
  services,
  handleSubmit,
  initialize,
  initialValues,
  onSubmit,
}) => {
  useEffect(() => {
    const toUpdate = item || {};
    let date = new Date(toUpdate.date);
    if (isNaN(date)) {
      date = new Date();
    }
    initialize({
      ...initialValues,
      ...toUpdate,
      date: date.toISOString().substring(0, 10),
    });
  }, [
    item,
    initialize,
    initialValues,
  ]);

  return (
    <Form
      onSubmit={handleSubmit(onSubmit)}
    >
      <Field
        name="slug"
        label="Ссылка"
        component={AdminField}
      />

     <Field
        name="title"
        label="Заголовок"
        component={AdminField}
      />

      <Field
        name="service"
        label="Услуга"
        options={services}
        component={SelectField}
      />

      <Field
        name="client"
        label="Клиент"
        component={AdminField}
      />

      <Field
        name="date"
        label="Дата"
        type="date"
        component={AdminField}
      />

      <Field
        name="image"
        label="Изображение"
        component={ImageField}
      />

      <Field
        name="text"
        label="Статья"
        component={MarkdownPreview}
      />

      {link && <Form.Group>
        <Button
          variant="link"
          href={link}
        >
          Перейти
        </Button>
      </Form.Group>}

      <Form.Group>
        <Button
          className="my-2"
          variant="success"
          type="submit"          
        >
          Сохранить
        </Button>
      </Form.Group>
    </Form>
  );
}

ProjectForm = reduxForm({
  form: FORM_NAME,
  initialValues: {
    slug: '',
    title: '',
    client: '',
    serviceId: null,
    image: '',
    text: '',
  },
})(ProjectForm);

export default ProjectForm;
