// front/src/views/Home.vue
<template>
  <div class="home">
    <div
      v-if="page"
      v-html="page.html"
    />

    <what-we-do
      title="Что Мы Делаем"
      :links="services"
    />
    <latest-projects
      title="Последние проекты"
      :projects="projects"
    />
  </div>
</template>

<script>
import {
  mapActions,
  mapState,
} from 'vuex';
import config from '@/helpers/config';

export default {
  name: 'Home',
  components: {
    WhatWeDo: () => import('../components/WhatWeDo.vue'),
    LatestProjects: () => import('../components/LatestProjects.vue'),
  },
  computed: {
    ...mapState([
      'services',
      'projects',
      'page',
    ]),
  },
  methods: {
    ...mapActions([
      'fetchServices',
      'fetchLatestProjects',
      'fetchPage',
    ]),
  },
  mounted() {
    this.fetchServices();
    this.fetchLatestProjects();
    this.fetchPage(config.defaultPage);
  },
};
</script>

// front/src/views/Home.jsx
import React from 'react';
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import LatestProjects from '../components/LatestProjects';
import WhatWeDo from '../components/WhatWeDo';
import config from '../helpers/config';
import { fetchPage, selectPage } from '../reducers/pageSlice';
import { fetchLatestProjects, selectProjects } from '../reducers/projectSlice';
import { fetchServices, selectServices } from '../reducers/serviceSlice';

function Home() {
  const {
    defaultPage,
  } = config

  const dispatch = useDispatch();

  const page = useSelector(selectPage);
  const projects = useSelector(selectProjects);
  const services = useSelector(selectServices);

  useEffect(() => {
    dispatch(fetchServices());
    dispatch(fetchLatestProjects());
    dispatch(fetchPage(defaultPage));
  }, [
    dispatch,
    defaultPage,
  ]);

  return (
    <div className="home main-page">
      { page && <div
        className="main-page-content"
        dangerouslySetInnerHTML={{
          __html: page.html,
        }}
      /> }  

      <WhatWeDo
        title="Что Мы Делаем"
        links={services}
      />

      <LatestProjects
        title="Последние проекты"
        projects={projects}
      />
  </div>
  );
}

export default Home;
